# Generated by Django 4.0.5 on 2022-06-19 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_update_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
