# Generated by Django 4.0.5 on 2022-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_company_last_update_time_alter_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rank',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
